### Gram - Schmidt process

This assignment contains a function to perform the Gram-Schmidt procedure, which takes a list of vectors and forms an orthonormal basis from this set. As a corollary, the procedure allows us to determine the dimension of the space spanned by the basis vectors, which is equal to or less than the space which the vectors sit.

Building on last assignment, in this exercise you will need to select whole columns at a time. This can be done with A[:, m] which will select the m'th column (starting at zero). In this exercise, you will need to take the dot product between vectors. This can be done using the @ operator. To dot product vectors u and v it writes as u @ v

In [3]:
import numpy as np
import numpy.linalg as la

verySmallNumber = 1e-14 # That's 1×10⁻¹⁴ = 0.00000000000001 lol


# We'll use a for-loop here to iterate the process for each vector.
def gsBasis(A) :
    B = np.array(A, dtype=np.float_) # Make B as a copy of A, since we're going to alter it's values.
    # Loop over all vectors, starting with zero, label them with i
    for i in range(B.shape[1]) :
        # Inside that loop, loop over all previous vectors, j, to subtract.
        for j in range(i) :
            # We need the current vector B[:, i] and a previous vector B[:, j]
            B[:, i] = B[:, i] - B[:, i] @ B[:, j] * B[:, j]
        # Next insert code to do the normalisation test for B[:, i]
        # If there's anything left after that subtraction, then B[:, 1] is linearly independant of B[:, 0]
        # If this is the case, we can normalise it. Otherwise we'll set that vector to zero.
        if la.norm(B[:, i]) > verySmallNumber :
            B[:, i] = B[:, i] / la.norm(B[:, i])
        else :
            B[:, i] = np.zeros_like(B[:, i])
             
    # Finally, we return the result:
    return B

# This function uses the Gram-schmidt process to calculate the dimension
# spanned by a list of vectors.
# Since each vector is normalised to one, or is zero,
# the sum of all the norms will be the dimension.
def dimensions(A) :
    return np.sum(la.norm(gsBasis(A), axis=0))

### Testing the code

In [4]:
V = np.array([[1,0,2,6],
              [0,1,8,2],
              [2,8,3,1],
              [1,-6,2,3]], dtype=np.float_)

gsBasis(V)

array([[ 0.40824829, -0.1814885 ,  0.04982278,  0.89325973],
       [ 0.        ,  0.1088931 ,  0.99349591, -0.03328918],
       [ 0.81649658,  0.50816781, -0.06462163, -0.26631346],
       [ 0.40824829, -0.83484711,  0.07942048, -0.36063281]])

In [7]:
# See what happens for non-square matrices
A = np.array([[3,2,3],
              [2,5,-1],
              [2,4,8],
              [12,2,1]], dtype=np.float_)
print(gsBasis(A))
dimensions(A)

[[ 0.23643312  0.18771349  0.22132104]
 [ 0.15762208  0.74769023 -0.64395812]
 [ 0.15762208  0.57790444  0.72904263]
 [ 0.94573249 -0.26786082 -0.06951101]]


3.0

In [8]:
B = np.array([[6,2,1,7,5],
              [2,8,5,-4,1],
              [1,-6,3,2,8]], dtype=np.float_)
print(gsBasis(B))
dimensions(B)

[[ 0.93704257 -0.12700832 -0.32530002  0.          0.        ]
 [ 0.31234752  0.72140727  0.61807005  0.          0.        ]
 [ 0.15617376 -0.6807646   0.71566005  0.          0.        ]]


3.0

In [9]:
# Now let's see what happens when we have one vector that is a linear combination of the others.
C = np.array([[1,0,2],
              [0,1,-3],
              [1,0,2]], dtype=np.float_)
print(gsBasis(C))
dimensions(C)

[[0.70710678 0.         0.        ]
 [0.         1.         0.        ]
 [0.70710678 0.         0.        ]]


2.0